# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36d84730f7fd6fc75f376e99f30f5a2d5883f6847d5715c0cb208e8f768c384dc959612854764bac9c64d6793ce5f3ef73f3f05c0073760ae406b3aed6b33adc

test:
  secret_key_base: b52fcf5a1eaf9285bdb1133d3db7926c9522ec4487a16f1c6528968060aafeb371061520fffbe59181cc409ba74cd356785351258aab2d68419a06c215b6e0da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
